package albedo

import (
	"github.com/genshinsim/gcsim/pkg/core/attacks"
	"github.com/genshinsim/gcsim/pkg/core/attributes"
	"github.com/genshinsim/gcsim/pkg/core/combat"
	"github.com/genshinsim/gcsim/pkg/core/construct"
	"github.com/genshinsim/gcsim/pkg/core/event"
	"github.com/genshinsim/gcsim/pkg/core/glog"
	"github.com/genshinsim/gcsim/pkg/core/info"
	"github.com/genshinsim/gcsim/pkg/core/player/character"
	"github.com/genshinsim/gcsim/pkg/core/player/shield"
	"github.com/genshinsim/gcsim/pkg/modifier"
)

const (
	// Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for 30s:
	// • Unleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning. Each stack of Fatal Reckoning consumed increases the DMG dealt by Fatal Blossoms and Rite of Progeniture: Tectonic Tide's burst DMG by 30% of Albedo's DEF.
	// • This effect stacks up to 4 times.
	c2key                 = "albedo-c2"
	c6TransientBlossomDMG = "albedo-c6-dmg"
)

func (c *char) c1Init() {
	if c.Base.Cons < 1 {
		return
	}
	c.c1Buff = make([]float64, attributes.EndStatType)
	c.c1Buff[attributes.DEFP] = 0.5
}

func (c *char) c1OnSkillTick() {
	if c.Base.Cons < 1 {
		return
	}
	c.AddEnergy("albedo-c1", 1.2)
	c.Core.Log.NewEvent("c1 restoring energy", glog.LogCharacterEvent, c.Index())
	c.AddStatMod(character.StatMod{
		Base:         modifier.NewBase("albedo-c1", 20*60),
		AffectedStat: attributes.DEFP,
		Amount: func() ([]float64, bool) {
			return c.c1Buff, true
		},
	})
}

func (c *char) c2OnSkillTick() {
	if c.Base.Cons < 2 {
		return
	}

	if !c.StatusIsActive(c2key) {
		c.c2stacks = 0
	}
	c.AddStatus(c2key, 1800, true) // lasts 30 sec
	c.c2stacks++
	if c.c2stacks > 4 {
		c.c2stacks = 4
	}

	if c.c2stacks < 4 {
		return
	}

	if c.Core.Player.Active() == c.Index() {
		return
	}

	ai := info.AttackInfo{
		ActorIndex: c.Index(),
		Abil:       "Fatal Blossom (C2)",
		AttackTag:  attacks.AttackTagElementalBurst,
		ICDTag:     attacks.ICDTagElementalBurst,
		ICDGroup:   attacks.ICDGroupDefault,
		StrikeType: attacks.StrikeTypeBlunt,
		PoiseDMG:   100,
		Element:    attributes.Geo,
		Durability: 25,
		Mult:       3,
		UseDef:     true,
	}

	// generate 3 blossoms
	maxBlossoms := 3
	enemies := c.Core.Combat.RandomEnemiesWithinArea(c.skillArea, nil, maxBlossoms)
	tracking := len(enemies)
	var center info.Point
	for i := range maxBlossoms {
		if i < tracking {
			// each blossom targets a separate enemy if possible
			center = enemies[i].Pos()
		} else {
			// if a blossom has no enemy then it randomly spawns in the skill area
			center = info.CalcRandomPointFromCenter(c.skillArea.Shape.Pos(), 0.5, 9.5, c.Core.Rand)
		}
		// Blossoms are generated on a slight delay from initial hit
		// TODO: no precise frame data for time between Blossoms
		c.Core.QueueAttackWithSnap(
			ai,
			c.bloomSnapshot,
			combat.NewCircleHitOnTarget(center, nil, 3),
			i*5,
		)
	}
	c.c2stacks = 0
	c.a4()
}

// C4:
// Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by 30%.
func (c *char) c4(lastConstruct int) func() {
	return func() {
		// don't apply / check again if skill was recast
		if c.lastConstruct != lastConstruct {
			return
		}
		// don't apply / check again if skill isn't active anymore
		if !c.skillActive {
			return
		}

		// apply C4 buff to active char for 1s if within skill area
		inSkillArea := c.Core.Combat.Player().IsWithinArea(c.skillArea)
		if inSkillArea {
			active := c.Core.Player.ActiveChar()
			m := make([]float64, attributes.EndStatType)
			m[attributes.DmgP] = 0.3
			active.AddAttackMod(character.AttackMod{
				Base: modifier.NewBaseWithHitlag("albedo-c4", 60), // 1s
				Amount: func(atk *info.AttackEvent, _ info.Target) ([]float64, bool) {
					if atk.Info.AttackTag != attacks.AttackTagPlunge {
						return nil, false
					}
					return m, true
				},
			})
		}

		// check again in 0.3s
		c.Core.Tasks.Add(c.c4(lastConstruct), 18)
	}
}

// C6:
// Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by 17%.
func (c *char) c6(lastConstruct int) func() {
	return func() {
		// don't apply / check again if skill was recast
		if c.lastConstruct != lastConstruct {
			return
		}
		// don't apply / check again if skill isn't active anymore
		if !c.skillActive {
			return
		}

		// apply C6 buff to active char for 1s if they are protected by crystallize and within the skill area
		crystallizeShield := c.Core.Player.Shields.Get(shield.Crystallize) != nil
		luanrCrystallize := c.Core.Constructs.CountByType(construct.GeoConstructLunarCrystallize) > 0
		inSkillArea := c.Core.Combat.Player().IsWithinArea(c.skillArea)
		if (crystallizeShield || luanrCrystallize) && inSkillArea {
			active := c.Core.Player.ActiveChar()
			m := make([]float64, attributes.EndStatType)
			m[attributes.DmgP] = 0.17
			active.AddStatMod(character.StatMod{
				Base:         modifier.NewBase("albedo-c6", 60), // 1s
				AffectedStat: attributes.DmgP,
				Amount: func() ([]float64, bool) {
					return m, true
				},
			})
		}

		// check again in 0.3s
		c.Core.Tasks.Add(c.c6(lastConstruct), 18)
	}
}

func (c *char) c6Init() {
	if c.Base.Cons < 6 {
		return
	}
	if !c.IsHexerei {
		return
	}

	c.Core.Events.Subscribe(event.OnEnemyHit, func(args ...any) bool {
		atk := args[1].(*info.AttackEvent)
		if atk.Info.ActorIndex != c.Index() {
			return false
		}

		if atk.Info.AttackTag != attacks.AttackTagElementalArt {
			return false
		}
		// Can't be triggered by itself when refreshing
		if atk.Info.Abil == skillAbilInitial {
			return false
		}

		if !c.StatusIsActive(c6TransientBlossomDMG) {
			return false
		}

		atk.Info.FlatDmg += 2.5 * c.TotalDef(false)

		return false
	}, "albedo-c6-hook")
}

func (c *char) c6OnBurst() bool {
	if c.Base.Cons < 6 {
		return false
	}
	if !c.IsHexerei {
		return false
	}

	if c.getAureliths() == 0 {
		return false
	}

	// destory all aurelith
	c.aureliths[0] = 0
	c.aureliths[1] = 0
	c.oldestAurelith = 0

	c.AddStatus(c6TransientBlossomDMG, 20*60, true)

	return true
}
