id: 10000131
key: "nicole"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_MONDSTADT
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Nicole"
stats: {
   base_hp: 810
   base_atk: 26.63
   base_def: 43.8
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 695
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37.55
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.9457
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1188
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.23
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.05
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1846
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 99.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.67
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2340
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 126.48
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.89
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2834
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 153.16
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.11
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3327
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.84
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 109.33
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 11062
   burst: 11065
   attack: 11061
}
name_text_hash_map: 113398050
