// Code generated by "pipeline"; DO NOT EDIT.
package nicole

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Nicole, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
        0.3518,
        0.3782,
        0.4046,
        0.4397,
        0.4661,
        0.4925,
        0.5277,
        0.5629,
        0.5980,
        0.6332,
        0.6684,
        0.7036,
        0.7476,
        0.7915,
        0.8355,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
        0.2963,
        0.3186,
        0.3408,
        0.3704,
        0.3926,
        0.4149,
        0.4445,
        0.4741,
        0.5038,
        0.5334,
        0.5630,
        0.5927,
        0.6297,
        0.6668,
        0.7038,
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
        0.4619,
        0.4965,
        0.5312,
        0.5774,
        0.6120,
        0.6466,
        0.6928,
        0.7390,
        0.7852,
        0.8314,
        0.8776,
        0.9238,
        0.9815,
        1.0392,
        1.0970,
	}
	// attack: charge = [3]
	charge = []float64{
        1.1232,
        1.2074,
        1.2917,
        1.4040,
        1.4882,
        1.5725,
        1.6848,
        1.7971,
        1.9094,
        2.0218,
        2.1341,
        2.2464,
        2.3868,
        2.5272,
        2.6676,
	}
	// skill: skill = [0]
	skill = []float64{
		1.3840,
        1.4878,
        1.5916,
        1.7300,
        1.8338,
        1.9376,
        2.0760,
        2.2144,
        2.3528,
        2.4912,
        2.6296,
        2.7680,
        2.9410,
        3.1140,
        3.2870,
	}
	// skill: shieldAtk = [3]
	shieldAtk = []float64{
		2.2118,
        2.3777,
        2.5436,
        2.7648,
        2.9307,
        3.0966,
        3.3178,
        3.5389,
        3.7601,
        3.9813,
        4.2025,
        4.4237,
        4.7002,
        4.9766,
        5.2531,
	}
	// skill: shieldFlat = [3]
	shieldFlat = []float64{
        1387,
        1525,
        1676,
        1837,
        2011,
        2196,
        2392,
        2600,
        2820,
        3051,
        3294,
        3548,
        3814,
        4091,
        4380,
	}
	// skill: skillBuff = [3]
	skillBuff = []float64{
        0.0825,
        0.0900,
        0.0975,
        0.1050,
        0.1125,
        0.1200,
        0.1275,
        0.1350,
        0.1425,
        0.1500,
        0.1590,
        0.1680,
        0.1770,
        0.1860,
        0.1950,
	}
	// skill: skillBuffCap = [3]
	skillBuffCap = []float64{
        330,
        360,
        390,
        420,
        450,
        480,
        510,
        540,
        570,
        600,
        636,
        672,
        708,
        744,
        780,
	}
	// burst: burst = [0]
	burst = []float64{
        3.1680,
        3.4056,
        3.6432,
        3.9600,
        4.1976,
        4.4352,
        4.7520,
        5.0688,
        5.3856,
        5.7024,
        6.0192,
        6.3360,
        6.7320,
        7.1280,
        7.5240,
	}
	// burst: burstProj = [1]
	burstProj = []float64{
        0.9900,
        1.0800,
        1.1700,
        1.2600,
        1.3500,
        1.4400,
        1.5300,
        1.6200,
        1.7100,
        1.8000,
        1.9080,
        2.0160,
        2.1240,
        2.2320,
        2.3400,
	}

)
