// Code generated by "pipeline"; DO NOT EDIT.
package lohen

import (
	_ "embed"

	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"travel"},
	5: {"collision"},
	6: {"collision"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Lohen, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		{attack_2},
		attack_3,
		{attack_4},
		attack_5,
	}
	skillAttack = [][][]float64{
		{skillAttack_1},
		{skillAttack_2},
		skillAttack_3,
		{skillAttack_4},
		skillAttack_5,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
        0.5399,
        0.5839,
        0.6278,
        0.6906,
        0.7345,
        0.7848,
        0.8538,
        0.9229,
        0.9919,
        1.0673,
        1.1426,
        1.2180,
        1.2933,
        1.3686,
        1.4440,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
        0.5644,
        0.6104,
        0.6563,
        0.7219,
        0.7679,
        0.8204,
        0.8926,
        0.9648,
        1.0370,
        1.1157,
        1.1945,
        1.2732,
        1.3520,
        1.4308,
        1.5095,
	}
	// attack: attack_4 = [3 3 3]
	attack_3 = [][]float64{
		{
			0.2542,
			0.2749,
			0.2956,
			0.3251,
			0.3458,
			0.3695,
			0.4020,
			0.4345,
			0.4670,
			0.5025,
			0.5380,
			0.5734,
			0.6089,
			0.6444,
			0.6798,
		},
		{
			0.2542,
			0.2749,
			0.2956,
			0.3251,
			0.3458,
			0.3695,
			0.4020,
			0.4345,
			0.4670,
			0.5025,
			0.5380,
			0.5734,
			0.6089,
			0.6444,
			0.6798,
		},
		{
			0.2542,
			0.2749,
			0.2956,
			0.3251,
			0.3458,
			0.3695,
			0.4020,
			0.4345,
			0.4670,
			0.5025,
			0.5380,
			0.5734,
			0.6089,
			0.6444,
			0.6798,
		},
	}

	// attack: attack_5 = [4]
	attack_4 = []float64{
        0.2542,
        0.2749,
        0.2956,
        0.3251,
        0.3458,
        0.3695,
        0.4020,
        0.4345,
        0.4670,
        0.5025,
        0.5380,
        0.5734,
        0.6089,
        0.6444,
        0.6798,
	}
		// attack: attack_3 = [2 2]
	attack_5 = [][]float64{
		{
			0.3686,
			0.3986,
			0.4286,
			0.4714,
			0.5014,
			0.5357,
			0.5829,
			0.6300,
			0.6772,
			0.7286,
			0.7800,
			0.8314,
			0.8829,
			0.9343,
			0.9857,
		},
		{
			0.5529,
			0.5979,
			0.6429,
			0.7072,
			0.7522,
			0.8036,
			0.8743,
			0.9450,
			1.0157,
			1.0929,
			1.1700,
			1.2472,
			1.3243,
			1.4015,
			1.4786,
		},
	}
	// attack: charge = [4]
	charge = []float64{
        0.6588,
        0.7124,
        0.7660,
        0.8426,
        0.8962,
        0.9575,
        1.0418,
        1.1260,
        1.2103,
        1.3022,
        1.3941,
        1.4860,
        1.5780,
        1.6699,
        1.7618,
	}
	// attack: attack_1 = [0]
	skillAttack_1 = []float64{
        0.8099,
        0.8758,
        0.9417,
        1.0359,
        1.1018,
        1.1771,
        1.2807,
        1.3843,
        1.4879,
        1.6009,
        1.7139,
        1.8269,
        1.9399,
        2.0529,
        2.1659,
	}
	// attack: attack_2 = [1]
	skillAttack_2 = []float64{
        0.8466,
        0.9156,
        0.9845,
        1.0829,
        1.1518,
        1.2306,
        1.3389,
        1.4472,
        1.5555,
        1.6736,
        1.7917,
        1.9099,
        2.028,
        2.1461,
        2.2643,
	}
	// attack: attack_4 = [3 3 3]
	skillAttack_3 = [][]float64{
		{
			0.3813,
			0.4123,
			0.4434,
			0.4877,
			0.5187,
			0.5542,
			0.603,
			0.6518,
			0.7005,
			0.7537,
			0.8069,
			0.8601,
			0.9133,
			0.9665,
			1.0198,
		},
		{
			0.3813,
			0.4123,
			0.4434,
			0.4877,
			0.5187,
			0.5542,
			0.603,
			0.6518,
			0.7005,
			0.7537,
			0.8069,
			0.8601,
			0.9133,
			0.9665,
			1.0198,
		},
		{
			0.3813,
			0.4123,
			0.4434,
			0.4877,
			0.5187,
			0.5542,
			0.603,
			0.6518,
			0.7005,
			0.7537,
			0.8069,
			0.8601,
			0.9133,
			0.9665,
			1.0198,
		},
	}
	skillAttack_4 = []float64{
        1.1284,
        1.2202,
        1.3121,
        1.4433,
        1.5351,
        1.6401,
        1.7844,
        1.9288,
        2.0731,
        2.2305,
        2.388,
        2.5454,
        2.7029,
        2.8603,
        3.0178,
	}
	skillAttack_5 = [][]float64{
		{
			0.5529,
			0.5979,
			0.6429,
			0.7072,
			0.7522,
			0.8036,
			0.8743,
			0.945,
			1.0157,
			1.0929,
			1.17,
			1.2472,
			1.3243,
			1.4015,
			1.4786,
		},
		{
			0.8293,
			0.8968,
			0.9643,
			1.0607,
			1.1282,
			1.2054,
			1.3115,
			1.4175,
			1.5236,
			1.6393,
			1.755,
			1.8708,
			1.9865,
			2.1022,
			2.2179,
		},
	}
	skillCharge = []float64{
        0.9881,
        1.0686,
        1.149,
        1.2639,
        1.3443,
        1.4362,
        1.5626,
        1.689,
        1.8154,
        1.9533,
        2.0912,
        2.2291,
        2.3669,
        2.5048,
        2.6427,
	}
	// skill: skillInital = [0]
	skillPierce = []float64{
        0.6,
        0.645,
        0.69,
        0.75,
        0.795,
        0.84,
        0.9,
        0.96,
        1.02,
        1.08,
        1.14,
        1.2,
        1.275,
        1.35,
        1.425,
	}
	// burst: burst = [0]
	burst = []float64{
        1.188,
        1.2771,
        1.3662,
        1.485,
        1.5741,
        1.6632,
        1.782,
        1.9008,
        2.0196,
        2.1384,
        2.2572,
        2.376,
        2.5245,
        2.673,
        2.8215,
	}
)
